"""Generate a markdown benchmark comparison report from stored JSON results.

Usage:
    python scripts/generate_report.py
    python scripts/generate_report.py --results-dir tests/benchmarks/results/
    python scripts/generate_report.py --output tests/benchmarks/results/comparison_table.md
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

BASELINES = {
    "NLI-only (SummaC)": {"halueval_auroc": 0.720, "fever_auroc": 0.700},
    "Retrieval-only (FActScore)": {"halueval_auroc": 0.680, "fever_auroc": 0.740},
    "SelfCheckGPT": {"halueval_auroc": 0.740, "fever_auroc": 0.690},
}

DATASET_FILE_MAP = {
    "HaluEval QA": "halueval_results.json",
    "FEVER (validation)": "fever_results.json",
}


def load_results(results_dir: Path) -> dict[str, dict]:
    """Load all available JSON result files from the results directory."""
    loaded: dict[str, dict] = {}
    for dataset_name, filename in DATASET_FILE_MAP.items():
        path = results_dir / filename
        if path.exists():
            loaded[dataset_name] = json.loads(path.read_text())
    return loaded


def format_auroc(value: float | None) -> str:
    if value is None or (isinstance(value, float) and value != value):  # nan check
        return "—"
    return f"{value:.3f}"


def generate_comparison_table(results: dict[str, dict]) -> str:
    """Generate the full markdown comparison table."""
    halueval = results.get("HaluEval QA", {})
    fever = results.get("FEVER (validation)", {})

    lines = [
        "# Benchmark Comparison Table",
        "",
        "Evaluation of VeritasCore NLI Verifier vs published baselines.",
        "",
        f"- HaluEval QA: n={halueval.get('n_samples', '?')} samples",
        f"- FEVER: n={fever.get('n_samples', '?')} samples",
        "",
        "| Method | HaluEval AUROC | FEVER AUROC | Source |",
        "|--------|:--------------:|:-----------:|--------|",
    ]

    # Baselines
    for name, baseline in BASELINES.items():
        h_auroc = format_auroc(baseline.get("halueval_auroc"))
        f_auroc = format_auroc(baseline.get("fever_auroc"))
        lines.append(f"| {name} | {h_auroc} | {f_auroc} | Published |")

    # VeritasCore results
    h_auroc_vc = format_auroc(halueval.get("auroc"))
    f_auroc_vc = format_auroc(fever.get("auroc"))
    lines.append(f"| **VeritasCore (NLI Verifier)** | **{h_auroc_vc}** | **{f_auroc_vc}** | This work |")

    lines += [
        "",
        "## Detailed Results",
        "",
    ]

    # Per-dataset detail tables
    for dataset_name, result in results.items():
        lines += [
            f"### {dataset_name}",
            "",
            "| Metric | Value |",
            "|--------|-------|",
            f"| Samples evaluated | {result.get('n_samples', '?')} |",
            f"| AUROC | {format_auroc(result.get('auroc'))} |",
            f"| F1 | {result.get('f1', 0):.4f} |",
            f"| Precision | {result.get('precision', 0):.4f} |",
            f"| Recall | {result.get('recall', 0):.4f} |",
            f"| Avg latency/claim | {result.get('avg_latency_ms', 0):.1f} ms |",
            f"| P95 latency/claim | {result.get('p95_latency_ms', 0):.1f} ms |",
            "",
        ]

    lines += [
        "## Quality Gate Status",
        "",
        "| Gate | Target | Achieved | Status |",
        "|------|--------|----------|--------|",
    ]

    halueval_auroc = halueval.get("auroc", 0) or 0
    fever_auroc = fever.get("auroc", 0) or 0

    g2_status = "✅ PASS" if halueval_auroc >= 0.72 else "❌ FAIL"
    lines.append(f"| G2 — NLI AUROC ≥ 0.72 | 0.720 | {halueval_auroc:.3f} | {g2_status} |")

    g8_status = "✅ PASS" if (halueval_auroc > 0 and fever_auroc > 0) else "⏳ PENDING"
    lines.append(f"| G8 — ≥2 datasets compared | ≥2 datasets | {len(results)} | {g8_status} |")

    lines += ["", f"*Generated by `scripts/generate_report.py`*"]

    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate benchmark comparison report")
    parser.add_argument(
        "--results-dir",
        type=Path,
        default=Path("tests/benchmarks/results"),
        help="Directory containing benchmark JSON result files",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=None,
        help="Output markdown file path (default: <results-dir>/comparison_table.md)",
    )
    args = parser.parse_args()

    if not args.results_dir.exists():
        print(f"Results directory not found: {args.results_dir}")
        print("Run `python scripts/run_benchmarks.py` first.")
        return

    results = load_results(args.results_dir)

    if not results:
        print("No result JSON files found. Run benchmarks first.")
        return

    table_md = generate_comparison_table(results)

    output_path = args.output or (args.results_dir / "comparison_table.md")
    output_path.write_text(table_md, encoding="utf-8")
    print(f"Comparison table written → {output_path}")
    print()
    print(table_md)


if __name__ == "__main__":
    main()
